feature(pu): add ppo best_practice for argsloader
HansBug/argsloader pull request #1
Opened 2022-04-01 06:11 UTC by puyuan1996

add ppo best_practice for argsloader.

2022-04-03 02:19 UTC, HansBug commented
请在index.rst中补充新的行，否则这页无法文档实际上没有被添加 @puyuan1996 。

另外，可以用以下的命令本地编译文档

```shell
make docs  # build documentation
make -C ./docs clean  # clean documentation
```

2022-04-03 02:19 UTC, HansBug commented
请在index.rst中补充新的行，否则这页无法文档实际上没有被添加 @puyuan1996 。

另外，可以用以下的命令本地编译文档

```shell
make docs  # build documentation
make -C ./docs clean  # clean documentation
```

2022-04-08 05:53 UTC, HansBug requested changes

2022-04-08 05:53 UTC, HansBug commented on docs/source/best_practice/ppo/parse.demo.py
> +        grad_clip_type=cvalue('clip_norm', enum(GradClipType) | none()),
想了一下这里还是有点小问题，不过还是工具设计的问题。

容我想一想，然后后续补充进来。

2022-04-08 05:53 UTC, HansBug commented on docs/source/best_practice/ppo/parse.demo.py
> +        grad_clip_type=cvalue('clip_norm', enum(GradClipType) | none()),
刚刚新增了optional，已经合并到main分支。
可以将 `| none()`替换为`optional`，这样的写法处理起来会更准确
参见
* https://hansbug.github.io/argsloader/main/api_doc/units/base.html#argsloader.units.base.BaseUnit.optional
* https://hansbug.github.io/argsloader/main/api_doc/units/common.html#optional

@puyuan1996

2022-04-13 06:52 UTC, puyuan1996 commented on docs/source/best_practice/ppo/parse.demo.py
> +        grad_clip_type=cvalue('clip_norm', enum(GradClipType) | none()),
改好了哈，不好意思，之前没有看到。

2022-04-13 13:45 UTC, HansBug approved these changes

2022-04-13 13:45 UTC, merged

2022-04-13 13:45 UTC, HansBug commented
Merged, thank you for contributing.