feature(zjow): Add Best Practice for Rainbow RL Policy in Argsloader.
HansBug/argsloader pull request #4
Opened 2022-04-07 17:12 UTC by zjowowen

2022-04-08 06:03 UTC, HansBug requested changes

2022-04-08 06:03 UTC, HansBug commented on docs/source/best_practice/rainbow/parse.demo.py
> +    nstep=cvalue(3,number() >> positive.int()),
这里加个空格（强迫症表示看得难受 😿

2022-04-08 06:03 UTC, HansBug commented on docs/source/best_practice/rainbow/parse.demo.py
> +    AdvancedReplayBufferDict = 2
enum请使用大写+下划线的格式。

2022-04-12 05:51 UTC, zjowowen commented on docs/source/best_practice/rainbow/parse.demo.py
> +    nstep=cvalue(3,number() >> positive.int()),
已使用yapf添加空格和间距。

2022-04-12 05:51 UTC, zjowowen commented on docs/source/best_practice/rainbow/parse.demo.py
> +    AdvancedReplayBufferDict = 2
格式已修改。

2022-04-12 14:54 UTC, HansBug approved these changes

2022-04-12 14:54 UTC, merged

2022-04-12 14:54 UTC, HansBug commented
Merged, thank you for contributing.